=== Derekmwilson/diethardsteiner.github.io/sample-files/pdi/bridge-and-parent-child-closure-table/mondrian3.xsd
<!-- NOTE: This is just a schema automatically derived from a sample mondrian olap xml - it quite likely not complete and it will not enforce everything -->
<!-- I used following utility: http://devutilsonline.com/xsd-xml/generate-xsd-from-xml AND ADJUSTED IT MANUALLY -->
<!--<?xml version="1.0"?>-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="Schema" type="SchemaType"/>
  <xs:complexType name="TableType" mixed="true">
    <xs:sequence>
      <xs:element type="AggNameType" name="AggName" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="schema" use="optional"/>
  </xs:complexType>
  <xs:complexType name="AnnotationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AnnotationsType">
    <xs:sequence>
      <xs:element type="AnnotationType" name="Annotation" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LevelType" mixed="true">
    <xs:sequence>
      <xs:element type="AnnotationsType" name="Annotations" minOccurs="0"/>
      <xs:element type="KeyExpressionType" name="KeyExpression" minOccurs="0"/>
      <xs:element type="OrdinalExpressionType" name="OrdinalExpression" minOccurs="0"/>
      <xs:element type="PropertyType" name="Property" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="column" use="optional"/>
    <xs:attribute type="xs:string" name="nameColumn" use="optional"/>
    <xs:attribute type="xs:string" name="ordinalColumn" use="optional"/>
    <xs:attribute type="xs:string" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="uniqueMembers" use="optional"/>
    <xs:attribute type="xs:string" name="levelType" use="optional"/>
    <xs:attribute type="xs:string" name="hideMemberIf" use="optional"/>
    <xs:attribute type="xs:string" name="table" use="optional"/>
    <xs:attribute type="xs:string" name="visible" use="optional"/>
    <xs:attribute type="xs:string" name="approxRowCount" use="optional"/>
  </xs:complexType>
  <xs:complexType name="HierarchyType">
    <xs:sequence>
      <xs:element type="TableType" name="Table" minOccurs="0"/>
      <xs:element type="LevelType" name="Level" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="caption" use="optional"/>
    <xs:attribute type="xs:string" name="visible" use="optional"/>
    <xs:attribute type="xs:string" name="hasAll" use="optional"/>
    <xs:attribute type="xs:string" name="allMemberName" use="optional"/>
    <xs:attribute type="xs:string" name="allMemberCaption" use="optional"/>
    <xs:attribute type="xs:string" name="primaryKey" use="optional"/>
  </xs:complexType>
  <xs:complexType name="DimensionType" mixed="true">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="HierarchyType" name="Hierarchy"/>
      <xs:element type="TableType" name="Table"/>
      <xs:element type="DimensionUsageType" name="DimensionUsage">
        <xs:annotation>
          <xs:documentation>
    &lt;DimensionUsage source="Date" name="Estimated Bill Date" caption="Estimated Bill Date" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    &lt;DimensionUsage source="Year" name="Estimated Bill Year" caption="Estimated Bill Year" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    &lt;DimensionUsage source="Quarter" name="Estimated Bill Quarter" caption="Estimated Bill Quarter" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    &lt;DimensionUsage source="Month" name="Estimated Bill Month" caption="Estimated Bill Month" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="DimensionType" name="Dimension"/>
      <xs:element type="MeasureType" name="Measure"/>
      <xs:element type="CalculatedMemberType" name="CalculatedMember">
        <xs:annotation>
          <xs:documentation> Just for checking </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:choice>
    <xs:attribute type="xs:string" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="visible" use="optional"/>
    <xs:attribute type="xs:string" name="highCardinality" use="optional"/>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="foreignKey" use="optional"/>
    <xs:attribute type="xs:string" name="source" use="optional"/>
    <xs:attribute type="xs:string" name="caption" use="optional"/>
    <xs:attribute type="xs:string" name="cache" use="optional"/>
    <xs:attribute type="xs:string" name="enabled" use="optional"/>
  </xs:complexType>
  <xs:complexType name="AggFactCountType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="column" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AggForeignKeyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="factColumn" use="optional"/>
        <xs:attribute type="xs:string" name="aggColumn" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AggMeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="column" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AggLevelType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="column" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="collapsed" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AggNameType">
    <xs:sequence>
      <xs:element type="AggFactCountType" name="AggFactCount"/>
      <xs:element type="AggForeignKeyType" name="AggForeignKey" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="AggMeasureType" name="AggMeasure" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="AggLevelType" name="AggLevel"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="ignorecase" use="optional"/>
  </xs:complexType>
  <xs:complexType name="DimensionUsageType" mixed="true">
    <!--
    <xs:sequence>
      <xs:element type="HierarchyType" name="Hierarchy"/>
    </xs:sequence>
    -->
    <xs:attribute type="xs:string" name="source" use="optional"/>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="caption" use="optional"/>
    <xs:attribute type="xs:string" name="visible" use="optional"/>
    <xs:attribute type="xs:string" name="foreignKey" use="optional"/>
    <xs:attribute type="xs:string" name="highCardinality" use="optional"/>
    <xs:attribute type="xs:string" name="type" use="optional"/>
  </xs:complexType>
  <xs:complexType name="MeasureType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="column" use="optional"/>
        <xs:attribute type="xs:string" name="datatype" use="optional"/>
        <xs:attribute type="xs:string" name="formatString" use="optional"/>
        <xs:attribute type="xs:string" name="aggregator" use="optional"/>
        <xs:attribute type="xs:string" name="visible" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CalculatedMemberType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="caption" use="optional"/>
        <xs:attribute type="xs:string" name="formatString" use="optional"/>
        <xs:attribute type="xs:string" name="formula" use="optional"/>
        <xs:attribute type="xs:string" name="dimension" use="optional"/>
        <xs:attribute type="xs:string" name="visible" use="optional"/>
        <xs:attribute type="xs:string" name="description" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CubeType" mixed="true">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="TableType" name="Table"/>
      <xs:element type="DimensionUsageType" name="DimensionUsage">
        <xs:annotation>
          <xs:documentation>
    &lt;DimensionUsage source="Date" name="Estimated Bill Date" caption="Estimated Bill Date" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    &lt;DimensionUsage source="Year" name="Estimated Bill Year" caption="Estimated Bill Year" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    &lt;DimensionUsage source="Quarter" name="Estimated Bill Quarter" caption="Estimated Bill Quarter" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    &lt;DimensionUsage source="Month" name="Estimated Bill Month" caption="Estimated Bill Month" visible="true" foreignKey="estimated_bill_date_tk" highCardinality="false"/&gt;
    </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="DimensionType" name="Dimension"/>
      <xs:element type="MeasureType" name="Measure"/>
      <xs:element type="CalculatedMemberType" name="CalculatedMember">
        <xs:annotation>
          <xs:documentation> Just for checking </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="HierarchyType" name="Hierarchy"/>
    </xs:choice>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="visible" use="optional"/>
    <xs:attribute type="xs:string" name="cache" use="optional"/>
    <xs:attribute type="xs:string" name="enabled" use="optional"/>
    <xs:attribute type="xs:string" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="highCardinality" use="optional"/>
    <xs:attribute type="xs:string" name="foreignKey" use="optional"/>
    <xs:attribute type="xs:string" name="source" use="optional"/>
    <xs:attribute type="xs:string" name="caption" use="optional"/>
  </xs:complexType>
  <xs:complexType name="SQLType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="dialect" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="OrdinalExpressionType">
    <xs:sequence>
      <xs:element type="SQLType" name="SQL"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="column" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="KeyExpressionType">
    <xs:sequence>
      <xs:element type="SQLType" name="SQL"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SchemaType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="DimensionType" name="Dimension" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="CubeType" name="Cube" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:float" name="metamodelVersion"/>
  </xs:complexType>
</xs:schema>

=== Derekmwilson/diethardsteiner.github.io/sample-files/pdi/bridge-and-parent-child-closure-table/olap-schema.mondrian.xml
<Schema name="Tutorial" metamodelVersion='3.0' xsi:noNamespaceSchemaLocation="mondrian3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
 
<!-- Level attribute description:
    
    * General *
    - name:
    - table (optional):
    - visible (optional):

    * Member Specific *
    - column: key column
    - type: data type of the value column
    - nameColumn (optional): internally used name, e.g. for MDX query
    - captionColumn (optional): value presented to end user 
    - ordinalColumn (optional): the column which specifies the order of the members
    - uniqueMembers 
    
    * Level Specific *
    - caption (optional): A string being displayed instead of the level's name. Can be localized from Properties file using #{propertyname}.
    - description (optional): Description of this level. Can be localized from Properties file using #{propertyname}.
    - levelType: Whether this is a regular or a time-related level
                             
 -->
    <Dimension name="Date" type="TimeDimension" visible="true" highCardinality="false">
        <Hierarchy name="Date" visible="true" hasAll="true" allMemberName="Total" allMemberCaption="Total" primaryKey="date_tk">
            <Table name="dim_date" schema="tutorial"/>
            <Level 
                name="Date" 
                column="date" 
                type="Date" 
                uniqueMembers="true" 
                levelType="TimeDays" 
                hideMemberIf="Never" 
                visible="true">
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[yyyy-MM-dd]]]>
                    </Annotation>
                </Annotations>
            </Level>
        </Hierarchy> 
        <Hierarchy name="Monthly Calendar" caption="Monthly Calendar" visible="true" hasAll="true" allMemberName="Total" allMemberCaption="Total" primaryKey="date_tk">
            <Table name="dim_date" schema="tutorial"/>
            <Level 
                name="Year" 
                column="year" 
                type="Integer" 
                uniqueMembers="false" 
                levelType="TimeYears" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                      <![CDATA[[yyyy]]]>
                    </Annotation>
                </Annotations>
            </Level>
            <!-- Note: 
                We can achieve two different sets of behaviours here:
                1) If the user doesn't use the parent year in the analysis, the quarter is displayed as 4 distinct values
                  , repeated over and over again without showing the context of the parent: 
                    - in this case define only quarter as the key column
                2) The quarter is displayed in relation to the year: 
                    - in this case define year and quarter as key column
                Below the second option is implemented.
            -->    
            <Level 
                name="Quarter" 
                column="year_quarter"
                type="Integer"  
                nameColumn="quarter"
                captionColumn="year_quarter_label"
                ordinalColumn="year_quarter"  
                uniqueMembers="false" 
                levelType="TimeQuarters" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[yyyy].[Q]]]>
                    </Annotation>
                </Annotations>
            </Level>
            <Level 
                name="Month" 
                column="year_month"
                type="Integer" 
                nameColumn="month" 
                captionColumn="year_month_label"
                ordinalColumn="year_month" 
                uniqueMembers="false" 
                levelType="TimeMonths" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[yyyy].[Q].[M]]]>
                    </Annotation>
                </Annotations>
            </Level>
            <Level 
                name="Day of the Month" 
                column="date_tk" 
                type="Integer" 
                nameColumn="day_of_month"
                captionColumn="day_of_month" 
                ordinalColumn="date_tk" 
                uniqueMembers="true" 
                levelType="TimeDays"
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[yyyy].[Q].[M].[d]]]>
                    </Annotation>
                </Annotations>
            </Level>
        </Hierarchy>	
        <Hierarchy name="Weekly Calendar" caption="Weekly Calendar" visible="true" hasAll="true" allMemberName="Total" allMemberCaption="Total" primaryKey="date_tk">
            <Table name="dim_date" schema="tutorial"/>
            <Level 
                name="Year" 
                column="iso8601_year" 
                type="Integer" 
                uniqueMembers="false" 
                levelType="TimeYears" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[YYYY]]]>
                    </Annotation>
                </Annotations>
            </Level>
            <Level 
                name="Week" 
                column="iso8601_year_week" 
                type="Integer" 
                nameColumn="iso8601_week"
                captionColumn="iso8601_year_week_label"  
                ordinalColumn="iso8601_year_week" 
                uniqueMembers="false" 
                levelType="TimeWeeks" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[YYYY].[w]]]>
                    </Annotation>
                </Annotations>
            </Level>
            <Level 
                name="Day of the Week" 
                column="date_tk" 
                type="Integer" 
                nameColumn="iso8601_day_of_week" 
                captionColumn="iso8601_day_of_week"
                ordinalColumn="date_tk" 
                uniqueMembers="true" 
                levelType="TimeDays" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Property name="Label" column="dow_label" type="String"/>
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[yyyy].[w].[e]]]>
                    </Annotation>
                </Annotations>
            </Level>
        </Hierarchy>       
    </Dimension>
    <Dimension name="Date Alt" type="TimeDimension" visible="true" highCardinality="false">
        <Hierarchy name="Date" visible="true" hasAll="true" allMemberName="Total" allMemberCaption="Total" primaryKey="date_tk">
            <Table name="dim_date" schema="tutorial"/>
            <Level 
                name="Date" 
                column="date" 
                type="Date" 
                uniqueMembers="true" 
                levelType="TimeDays" 
                hideMemberIf="Never" 
                visible="true">
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[yyyy-MM-dd]]]>
                    </Annotation>
                </Annotations>
            </Level>
        </Hierarchy> 
        <Hierarchy name="Monthly Calendar" caption="Monthly Calendar" visible="true" hasAll="true" allMemberName="Total" allMemberCaption="Total" primaryKey="date_tk">
            <Table name="dim_date" schema="tutorial"/>
            <Level 
                name="Year" 
                column="year" 
                type="Integer" 
                uniqueMembers="false" 
                levelType="TimeYears" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                      <![CDATA[[yyyy]]]>
                    </Annotation>
                </Annotations>
            </Level>
            <!-- Note: 
                We can achieve two different sets of behaviours here:
                1) If the user doesn't use the parent year in the analysis, the quarter is displayed as 4 distinct values
                    , which get repeated over and over again, so it is difficult to understand to which year the values belong e.g: 
                    - in this case define only quarter as the key column
                2) The quarter is displayed in relation to the year: 
                    - in this case define year and quarter as key column
                Below the second option is implemented.
            -->    
            <Level 
                name="Quarter" 
                column="quarter"
                type="Integer" 
                uniqueMembers="false" 
                levelType="TimeQuarters" 
                hideMemberIf="Never" 
                visible="true" 
            >
                <Annotations>
                    <Annotation name="AnalyzerDateFormat">
                    <![CDATA[[yyyy].[Q]]]>
                    </Annotation>
                </Annotations>
            </Level>
            <Level 
                name="Month" 
                column="month"
                type="Integer" 
                uniqueMembers="false" 
                levelType="TimeMonths"
